name: ECHorses
description: Protect horses from griefers
author: Emil Ekstrom aka Uncle_Emil. On bukkit forums known as Ekstemi
website: http://ekstemicraft.com
main: com.ekstemicraft.plugin.echorses.ECHorses
version: 1.0
commands:
    horseunclaim:
        description: Unclaim horse. Execute the command, and right click the horse
        usage: /<command>
  